name: Test Pipeline

on:
  push:
    branches:
      - '*'
      - '!gh-pages'   # excludes master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies for your project
      - name: Install Dependencies
        run: |
          pip install -e .[test]
          pip install sphinx

      # Run tests
      - name: Run Tests
        run: |
            cd tests
            pytest test_tree.py

      # Build Sphinx documentation
      - name: Generate Sphinx Documentation
        run: |
          cd doc
          make html
